apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: activity-tracking-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: globex-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: 'activity-tracking'
    repoURL: {{git_repository_url}}
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  